package bench

import (
	"fmt"
	"os"
	"strings"
	"testing"

	wonton "github.com/deepnoodle-ai/wonton/runewidth"
	gorunewidth "github.com/mattn/go-runewidth"
	"github.com/rivo/uniseg"
)

// TestCompatCorpus runs a large, varied Unicode corpus through
// wonton/runewidth, go-runewidth v0.0.21, and uniseg v0.4.7 and records every
// string where the three implementations disagree on StringWidth.
//
// The purpose is not pass/fail (there will be disagreements — that is
// expected because the libraries target different Unicode versions and make
// different decisions about keycaps, VS16, and similar edge cases). The
// purpose is to produce a report at runewidth/testdata/compat-report.md
// classifying each disagreement.
//
// Run with:
//
//	cd runewidth/internal/bench && go test -run TestCompatCorpus
//
// The test is skipped in short mode.
func TestCompatCorpus(t *testing.T) {
	if testing.Short() {
		t.Skip("compat corpus skipped in short mode")
	}

	corpus := buildCorpus()
	t.Logf("corpus size: %d strings", len(corpus))

	type disagreement struct {
		kind       string
		input      string
		wontonW    int
		gorwW      int
		unisegW    int
		classification string
	}
	var disagreements []disagreement

	for _, tc := range corpus {
		w := wonton.StringWidth(tc.s)
		g := gorunewidth.StringWidth(tc.s)
		u := uniseg.StringWidth(tc.s)
		if w == g && g == u {
			continue
		}
		disagreements = append(disagreements, disagreement{
			kind:           tc.kind,
			input:          tc.s,
			wontonW:        w,
			gorwW:          g,
			unisegW:        u,
			classification: classify(tc.s, w, g, u),
		})
	}

	t.Logf("%d disagreements across %d corpus entries", len(disagreements), len(corpus))

	// Write the report.
	var sb strings.Builder
	fmt.Fprintf(&sb, "# runewidth compatibility corpus report\n\n")
	fmt.Fprintf(&sb, "Generated by `runewidth/internal/bench.TestCompatCorpus`.\n\n")
	fmt.Fprintf(&sb, "Corpus size: %d strings. Disagreements: %d.\n\n", len(corpus), len(disagreements))
	fmt.Fprintf(&sb, "Columns: `W` = wonton/runewidth, `R` = go-runewidth v0.0.21, `U` = uniseg v0.4.7.\n\n")
	fmt.Fprintf(&sb, "| Kind | Input (hex) | W | R | U | Classification |\n")
	fmt.Fprintf(&sb, "|------|-------------|--:|--:|--:|----------------|\n")
	for _, d := range disagreements {
		fmt.Fprintf(&sb, "| %s | `%s` | %d | %d | %d | %s |\n",
			d.kind, toHex(d.input), d.wontonW, d.gorwW, d.unisegW, d.classification)
	}

	const reportPath = "../../testdata/compat-report.md"
	want := []byte(sb.String())

	if os.Getenv("UPDATE_COMPAT_REPORT") == "1" {
		if err := os.MkdirAll("../../testdata", 0755); err != nil {
			t.Fatalf("mkdir: %v", err)
		}
		if err := os.WriteFile(reportPath, want, 0644); err != nil {
			t.Fatalf("write report: %v", err)
		}
		t.Logf("wrote %s (%d bytes)", reportPath, len(want))
		return
	}

	got, err := os.ReadFile(reportPath)
	if err != nil {
		t.Fatalf("read report: %v (rerun with UPDATE_COMPAT_REPORT=1 to regenerate)", err)
	}
	if string(got) != string(want) {
		t.Fatalf("%s is stale; rerun with UPDATE_COMPAT_REPORT=1", reportPath)
	}
}

type corpusEntry struct {
	kind string
	s    string
}

func buildCorpus() []corpusEntry {
	var c []corpusEntry
	add := func(kind, s string) { c = append(c, corpusEntry{kind, s}) }

	// Pure ASCII.
	add("ascii", "Hello, World!")
	add("ascii", "The quick brown fox jumps over the lazy dog.")

	// Latin with combining marks.
	add("combining", "e\u0301")                     // é
	add("combining", "noe\u0308l")                  // noël
	add("combining", "a\u0300\u0301\u0302")         // a with three diacritics
	add("combining", "e\u0301e\u0301e\u0301e\u0301") // multiple
	// Precomposed equivalent:
	add("latin_precomp", "é")
	add("latin_precomp", "noël")

	// CJK.
	add("cjk", "中文")
	add("cjk", "日本語テスト")
	add("cjk", "한국어")
	add("cjk", "繁體中文")

	// RTL scripts.
	add("rtl", "مرحبا")       // Arabic
	add("rtl", "שלום")        // Hebrew
	add("rtl", "بلند")        // Persian

	// Indic (exercises GB9c).
	add("indic", "क\u094dत")                    // Devanagari KA + VIRAMA + TA
	add("indic", "क\u094d\u200dत")              // With ZWJ
	add("indic", "\u0915\u094D\u0915\u094D\u0924") // KA VIRAMA KA VIRAMA TA
	add("indic_tamil", "தமிழ்")
	add("indic_bengali", "বাংলা")

	// Plain emoji.
	add("emoji", "😀")
	add("emoji", "❤")         // text-default
	add("emoji", "❤\uFE0F")    // emoji with VS16
	add("emoji", "⭐")         // emoji default
	add("emoji", "⚠")         // text default
	add("emoji", "⚠\uFE0F")    // warning with VS16

	// ZWJ sequences.
	add("zwj", "\U0001F468\u200D\U0001F469\u200D\U0001F467\u200D\U0001F466") // family
	add("zwj", "\U0001F469\u200D\U0001F4BB")                                  // woman technologist
	add("zwj", "\U0001F3F3\uFE0F\u200D\U0001F308")                            // rainbow flag
	add("zwj", "\U0001F3F4\u200D\u2620\uFE0F")                                // pirate flag

	// Skin tone modifiers.
	add("skin_tone", "\U0001F44B\U0001F3FD")
	add("skin_tone", "\U0001F44D\U0001F3FF")
	add("skin_tone", "\U0001F469\U0001F3FB\u200D\U0001F4BB")

	// Regional indicators (flags).
	add("flag", "\U0001F1FA\U0001F1F8")                                     // US
	add("flag", "\U0001F1EF\U0001F1F5")                                     // JP
	add("flag", "\U0001F1FA\U0001F1F8\U0001F1EF\U0001F1F5")                 // two flags
	add("flag_tagged", "\U0001F3F4\U000E0067\U000E0062\U000E0065\U000E006E\U000E0067\U000E007F") // England tag

	// Keycap sequences.
	add("keycap", "#\uFE0F\u20E3")
	add("keycap", "*\uFE0F\u20E3")
	add("keycap", "0\uFE0F\u20E3")
	add("keycap", "9\uFE0F\u20E3")

	// Width > 2.
	add("wide_dash", "a\u2E3Ab")
	add("wide_dash", "\u2E3B")

	// Very long mixed strings.
	add("long_mixed", strings.Repeat("Hello 世界 👋🏽 ", 100))

	return c
}

// classify heuristically labels the row so the report is scannable.
func classify(s string, w, r, u int) string {
	if w == u && u != r {
		return "wonton matches uniseg; go-runewidth differs"
	}
	if w == r && r != u {
		return "wonton matches go-runewidth; uniseg differs"
	}
	if r == u && u != w {
		// Wonton is alone on this one.
		if strings.ContainsAny(s, "\uFE0E\uFE0F") && strings.Contains(s, "\u20E3") {
			return "keycap sequence — wonton forces width 2; uniseg and go-runewidth do not"
		}
		return "wonton differs from both others (known deviation)"
	}
	return "three-way disagreement"
}

func toHex(s string) string {
	var parts []string
	for _, r := range s {
		parts = append(parts, fmt.Sprintf("%04X", r))
	}
	return strings.Join(parts, " ")
}
